### ISSUE TITLE
fix: buggy popup section

### ISSUE THREAD

**Issue by 0xabdulkhaliq** [hirashabeer/Article-Preview-Component#1]
![image](https://github.com/hirashabeer/Article-Preview-Component/assets/92252895/c69c203b-f2cd-486f-a6b7-b08fc25edefb)

Currently the pop-up section has several bugs in it which we need to fix by refactoring the existing code with best practices.

**Comment by hirashabeer** [comment]
Sorry for the inconvenience @0xabdulkhalid 
I am not aware of GitHub featutes and functionality ..

**Comment by hirashabeer** [comment]
Is everything all right can you commit the changes in my repository

**Comment by 0xabdulkhaliq** [comment]
Issue has been successfully fixed and merged 🚀, So I'm gonna close this one.

Thank you for your support @hirashabeer ✨
